import type { LyricLine } from './useLyraStore';

export const mockLyricsDB: Record<string, LyricLine[]> = {
  // Adele - Easy On Me (Video ID: A7ZyTkycE7U)
  'A7ZyTkycE7U': [
    { text: "There is no gold in this river", start: 16, duration: 4 },
    { text: "That I've been washin' my hands in forever", start: 20.5, duration: 5 },
    { text: "I know there is hope in these waters", start: 26.5, duration: 4 },
    { text: "But I can't bring myself to swim", start: 31, duration: 4 },
    { text: "When I am drowning in this silence", start: 35, duration: 5 },
    { text: "Baby, let me in", start: 40.5, duration: 3.5 },
    { text: "Go easy on me, baby", start: 45.5, duration: 4.5 },
    { text: "I was still a child", start: 50.5, duration: 3.5 },
    { text: "Didn't get the chance to", start: 54.5, duration: 3.5 },
    { text: "Feel the world around me", start: 58.5, duration: 4 },
    { text: "I had no time to choose what I chose to do", start: 63, duration: 6 },
    { text: "So go easy on me", start: 70, duration: 5 },
    { text: "There is no room for things to change", start: 80.5, duration: 4.5 },
    { text: "When we are both so deeply stuck in our ways", start: 85.5, duration: 5.5 },
    { text: "You can't deny how hard I have tried", start: 91.5, duration: 5.5 },
    { text: "I changed who I was to put you both first", start: 97, duration: 5.5 },
    { text: "But now I give up", start: 103, duration: 3 },
    { text: "Go easy on me, baby", start: 107.5, duration: 4.5 },
    { text: "I was still a child", start: 112.5, duration: 3.5 },
    { text: "Didn't get the chance to", start: 116.5, duration: 3.5 },
    { text: "Feel the world around me", start: 120.5, duration: 4 },
    { text: "Had no time to choose what I chose to do", start: 125, duration: 6.5 },
    { text: "So go easy on me", start: 132, duration: 5 },
    { text: "[Piano Solo]", start: 139, duration: 12 },
    { text: "I had good intentions", start: 152, duration: 3 },
    { text: "And the highest hopes", start: 155.5, duration: 3 },
    { text: "But I know right now", start: 159, duration: 3 },
    { text: "It probably doesn't even show", start: 162.5, duration: 4.5 },
    { text: "Go easy on me, baby", start: 168.5, duration: 4.5 },
    { text: "I was still a child", start: 173.5, duration: 3.5 },
    { text: "I didn't get the chance to", start: 177.5, duration: 3.5 },
    { text: "Feel the world around me", start: 181.5, duration: 4 },
    { text: "Had no time to choose what I chose to do", start: 186, duration: 6.5 },
    { text: "So go easy on me", start: 193.5, duration: 6 }
  ],

  // The Weeknd - Blinding Lights (Video ID: 4NRXx6U8ABQ)
  '4NRXx6U8ABQ': [
    { text: "[Synthesizer Intro]", start: 0, duration: 6.5 },
    { text: "Yeah", start: 6.5, duration: 2 },
    { text: "I've been on my own for long enough", start: 9, duration: 4 },
    { text: "Maybe you can show me how to love, maybe", start: 13, duration: 5.5 },
    { text: "I'm going through withdrawals", start: 19, duration: 3 },
    { text: "You don't even have to do too much", start: 22, duration: 4 },
    { text: "You can turn me on with just a touch, baby", start: 26, duration: 5.5 },
    { text: "I look around and Sin City's cold and empty", start: 32, duration: 6 },
    { text: "No one's around to judge me", start: 38.5, duration: 3.5 },
    { text: "I can't see clearly when you're gone", start: 42, duration: 4 },
    { text: "I said, ooh, I'm blinded by the lights", start: 46.5, duration: 6.5 },
    { text: "No, I can't sleep until I feel your touch", start: 53.5, duration: 6 },
    { text: "I said, ooh, I'm drowning in the night", start: 60, duration: 6.5 },
    { text: "Oh, when I'm like this, you're the one I trust", start: 67, duration: 5.5 },
    { text: "(Hey, hey, hey!)", start: 73, duration: 3 },
    { text: "I'm running out of time", start: 76, duration: 3 },
    { text: "'Cause I can see the sun light up the sky", start: 79, duration: 4 },
    { text: "So I hit the road in overdrive, baby, oh", start: 83.5, duration: 6 },
    { text: "The city's cold and empty", start: 90, duration: 4 },
    { text: "No one's around to judge me", start: 94, duration: 3.5 },
    { text: "I can't see clearly when you're gone", start: 98, duration: 4 },
    { text: "I said, ooh, I'm blinded by the lights", start: 102.5, duration: 6.5 },
    { text: "No, I can't sleep until I feel your touch", start: 109.5, duration: 6 },
    { text: "I said, ooh, I'm drowning in the night", start: 116, duration: 6.5 },
    { text: "Oh, when I'm like this, you're the one I trust", start: 123, duration: 5.5 },
    { text: "[Synthesizer Solo]", start: 129, duration: 7.5 },
    { text: "I'm just walking by to let you know (by to let you know)", start: 137, duration: 4.5 },
    { text: "I can never say it on the phone (say it on the phone)", start: 142, duration: 4.5 },
    { text: "Will never let you go this time", start: 147.5, duration: 4 },
    { text: "I said, ooh, I'm blinded by the lights", start: 152, duration: 6.5 },
    { text: "No, I can't sleep until I feel your touch", start: 159, duration: 6 },
    { text: "(Hey, hey, hey!)", start: 165, duration: 3.5 },
    { text: "I said, ooh, I'm blinded by the lights", start: 169, duration: 6.5 },
    { text: "No, I can't sleep until I feel your touch", start: 176, duration: 6 },
    { text: "[Outro Synth fading]", start: 182, duration: 15 }
  ],

  // Queen - Bohemian Rhapsody (Video ID: fJ9rUzIMcZQ)
  'fJ9rUzIMcZQ': [
    { text: "Is this the real life? Is this just fantasy?", start: 1, duration: 8 },
    { text: "Caught in a landslide, no escape from reality", start: 9, duration: 8.5 },
    { text: "Open your eyes, look up to the skies and see", start: 18, duration: 9.5 },
    { text: "I'm just a poor boy, I need no sympathy", start: 28, duration: 7 },
    { text: "Because I'm easy come, easy go, little high, little low", start: 35.5, duration: 8.5 },
    { text: "Any way the wind blows doesn't really matter to me, to me", start: 44.5, duration: 10 },
    { text: "Mama, just killed a man", start: 56.5, duration: 5.5 },
    { text: "Put a gun against his head, pulled my trigger, now he's dead", start: 62.5, duration: 8.5 },
    { text: "Mama, life had just begun", start: 71.5, duration: 6 },
    { text: "But now I've gone and thrown it all away", start: 77.5, duration: 7 },
    { text: "Mama, ooh, didn't mean to make you cry", start: 85.5, duration: 8.5 },
    { text: "If I'm not back again this time tomorrow", start: 94.5, duration: 5 },
    { text: "Carry on, carry on as if nothing really matters", start: 99.5, duration: 7.5 },
    { text: "[Piano Bridge]", start: 107, duration: 10 },
    { text: "Too late, my time has come", start: 117.5, duration: 5.5 },
    { text: "Sends shivers down my spine, body's aching all the time", start: 123.5, duration: 8.5 },
    { text: "Goodbye, everybody, I've got to go", start: 132, duration: 6.5 },
    { text: "Gotta leave you all behind and face the truth", start: 139, duration: 7 },
    { text: "Mama, ooh (any way the wind blows)", start: 146.5, duration: 7.5 },
    { text: "I don't wanna die, I sometimes wish I'd never been born at all", start: 154, duration: 11 },
    { text: "[Guitar Solo]", start: 165, duration: 36 },
    { text: "I see a little silhouetto of a man", start: 201.5, duration: 4.5 },
    { text: "Scaramouche, Scaramouche, will you do the Fandango?", start: 206, duration: 4 },
    { text: "Thunderbolt and lightning, very, very frightening me", start: 210.5, duration: 4.5 },
    { text: "(Galileo) Galileo, (Galileo) Galileo, Galileo Figaro magnifico", start: 215, duration: 6 },
    { text: "I'm just a poor boy, nobody loves me", start: 221, duration: 4 },
    { text: "He's just a poor boy from a poor family", start: 225, duration: 3.5 },
    { text: "Spare him his life from this monstrosity", start: 228.5, duration: 4 },
    { text: "Easy come, easy go, will you let me go?", start: 232.5, duration: 3.5 },
    { text: "Bismillah! No, we will not let you go (Let him go!)", start: 236, duration: 4.5 },
    { text: "Bismillah! We will not let you go (Let him go!)", start: 240.5, duration: 3 },
    { text: "Bismillah! We will not let you go (Let me go!)", start: 243.5, duration: 2.5 },
    { text: "Will not let you go (Let me go!) Never let you go", start: 246, duration: 3.5 },
    { text: "Never, never, never let me go", start: 249.5, duration: 2 },
    { text: "No, no, no, no, no, no, no", start: 251.5, duration: 4 },
    { text: "Oh, mama mia, mama mia (Mama mia, let me go)", start: 255.5, duration: 3 },
    { text: "Beelzebub has a devil put aside for me, for me, for me", start: 258.5, duration: 8.5 },
    { text: "[Rock Section - Heavy Riffing]", start: 267, duration: 15 },
    { text: "So you think you can stone me and spit in my eye?", start: 282, duration: 4.5 },
    { text: "So you think you can love me and leave me to die?", start: 286.5, duration: 4.5 },
    { text: "Oh, baby, can't do this to me, baby", start: 291, duration: 5.5 },
    { text: "Just gotta get out, just gotta get right outta here", start: 296.5, duration: 6 },
    { text: "[Rock Outro]", start: 302.5, duration: 12 },
    { text: "Nothing really matters, anyone can see", start: 314.5, duration: 9 },
    { text: "Nothing really matters", start: 323.5, duration: 4.5 },
    { text: "Nothing really matters to me", start: 328, duration: 6 },
    { text: "[Gong Strike / Outro]", start: 334, duration: 20 }
  ],

  // Rick Astley - Never Gonna Give You Up (Video ID: dQw4w9WgXcQ)
  'dQw4w9WgXcQ': [
    { text: "[Dance Synth Intro]", start: 0, duration: 18.5 },
    { text: "We're no strangers to love", start: 18.5, duration: 4 },
    { text: "You know the rules and so do I (do I)", start: 22.5, duration: 4.5 },
    { text: "A full commitment's what I'm thinking of", start: 27, duration: 4.5 },
    { text: "You wouldn't get this from any other guy", start: 31.5, duration: 4 },
    { text: "I just wanna tell you how I'm feeling", start: 35.5, duration: 4.5 },
    { text: "Gotta make you understand", start: 40, duration: 3 },
    { text: "Never gonna give you up, never gonna let you down", start: 43, duration: 4.5 },
    { text: "Never gonna run around and desert you", start: 47.5, duration: 4 },
    { text: "Never gonna make you cry, never gonna say goodbye", start: 51.5, duration: 4.5 },
    { text: "Never gonna tell a lie and hurt you", start: 56, duration: 3.5 },
    { text: "We've known each other for so long", start: 59.5, duration: 4 },
    { text: "Your heart's been aching, but you're too shy to say it (say it)", start: 63.5, duration: 5 },
    { text: "Inside, we both know what's been going on", start: 68.5, duration: 4.5 },
    { text: "We know the game and we're gonna play it", start: 73, duration: 4 },
    { text: "And if you ask me how I'm feeling", start: 77, duration: 4 },
    { text: "Don't tell me you're too blind to see", start: 81, duration: 3.5 },
    { text: "Never gonna give you up, never gonna let you down", start: 84.5, duration: 4.5 },
    { text: "Never gonna run around and desert you", start: 89, duration: 4 },
    { text: "Never gonna make you cry, never gonna say goodbye", start: 93, duration: 4.5 },
    { text: "Never gonna tell a lie and hurt you", start: 97.5, duration: 4 },
    { text: "Never gonna give you up, never gonna let you down", start: 101.5, duration: 4.5 },
    { text: "Never gonna run around and desert you", start: 106, duration: 4 },
    { text: "Never gonna make you cry, never gonna say goodbye", start: 110, duration: 4.5 },
    { text: "Never gonna tell a lie and hurt you", start: 114.5, duration: 4 },
    { text: "[Keyboard Solo]", start: 118.5, duration: 16.5 },
    { text: "Ooh (give you up)", start: 135, duration: 2 },
    { text: "Ooh (give you up)", start: 137, duration: 2 },
    { text: "Never gonna give, never gonna give (give you up)", start: 139, duration: 4.5 },
    { text: "Never gonna give, never gonna give (give you up)", start: 143.5, duration: 3.5 },
    { text: "We've known each other for so long", start: 147, duration: 4 },
    { text: "Your heart's been aching, but you're too shy to say it", start: 151, duration: 5 },
    { text: "Inside, we both know what's been going on", start: 156, duration: 4.5 },
    { text: "We know the game and we're gonna play it", start: 160.5, duration: 4 },
    { text: "I just wanna tell you how I'm feeling", start: 164.5, duration: 4 },
    { text: "Gotta make you understand", start: 168.5, duration: 3 },
    { text: "Never gonna give you up, never gonna let you down", start: 171.5, duration: 4.5 },
    { text: "Never gonna run around and desert you", start: 176, duration: 4 },
    { text: "Never gonna make you cry, never gonna say goodbye", start: 180, duration: 4.5 },
    { text: "Never gonna tell a lie and hurt you", start: 184.5, duration: 4 },
    { text: "Never gonna give you up, never gonna let you down", start: 188, duration: 4.5 },
    { text: "Never gonna run around and desert you", start: 192.5, duration: 4 },
    { text: "Never gonna make you cry, never gonna say goodbye", start: 196.5, duration: 4.5 },
    { text: "Never gonna tell a lie and hurt you", start: 201, duration: 4 }
  ]
};
